version: 0.0
os: linux
files:
  - source: /k8s
    destination: /home/ec2-user/laboratorio_ci_cd/k8s
  - source: /scripts
    destination: /home/ec2-user/laboratorio_ci_cd/scripts
hooks:
  AfterInstall:
    - location: /home/ec2-user/laboratorio_ci_cd/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
