version: 0.0
os: linux
files:
  - source: /
    destination: 10ba-186-144-144-107.ngrok-free.app
hooks:
  AfterInstall:
    - location: scripts/deploy_to_minikube.sh
      timeout: 300
      runas: root
