version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"          # Reemplaza con tu región
    AWS_ACCOUNT_ID: "338287058401"   # Reemplaza con tu ID de cuenta de AWS
    ECR_REPOSITORY: "laboratorio_mafe"    # Reemplaza con tu repositorio de ECR
    IMAGE_TAG: "latest"              # Puedes cambiar esto a la versión que prefieras

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -y
      - apt-get install -y kubectl
      - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      - chmod +x minikube
      - mv minikube /usr/local/bin/
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Starting Minikube...
      - minikube start
      - echo Configuring kubectl to use Minikube context...
      - kubectl config use-context minikube
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - echo Tagging the Docker image...
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - echo Updating Kubernetes deployment...
      - sed -i "s|image: .*$|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
      - kubectl apply -f k8s/deployment.yaml --namespace=lab-mafe-ci-cd
      - kubectl apply -f k8s/service.yaml --namespace=lab-mafe-ci-cd

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - k8s/**
