version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"          # Reemplaza con tu región
    AWS_ACCOUNT_ID: "338287058401"   # Reemplaza con tu ID de cuenta de AWS
    ECR_REPOSITORY: "laboratorio_mafe"    # Reemplaza con tu repositorio de ECR
    IMAGE_TAG: "latest"              # Puedes cambiar esto a la versión que prefieras

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - echo Tagging the Docker image...
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
  post_deploy:
    commands:
      - chmod +x scripts/deploy_to_minikube.sh
      - ./scripts/start_server.sh

artifacts:
  files:
    - appspec.yml
    - deployment.yaml
    - service.yaml
    - scripts/**

