version: 0.2

phases:
  install:
    runtime-versions:
      docker: 26.1.4

  pre_build:
    commands:
      # Log in to Amazon ECR using AWS CLI
     aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 338287058401.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      # Build the Docker image
      docker build -t laboratorio_mafe .

      # Tag the Docker image
      docker tag laboratorio_mafe:latest 338287058401.dkr.ecr.us-west-2.amazonaws.com/laboratorio_mafe:latest

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      docker push 338287058401.dkr.ecr.us-west-2.amazonaws.com/laboratorio_mafe:latest

artifacts:
  files: []
