apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratorio-mafe
  labels:
    app: laboratorio-mafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laboratorio-mafe
  template:
    metadata:
      labels:
        app: laboratorio-mafe
    spec:
      containers:
      - name: laboratorio-mafe
        image: 338287058401.dkr.ecr.us-west-2.amazonaws.com/laboratorio_mafe:latest
        ports:
        - containerPort: 80
