#apiVersion: v1
#clusters:
#- cluster:
#    insecure-skip-tls-verify: true
#    server: https://192.168.49.2:8443
#  name: minikube
#contexts:
#- context:
#    cluster: minikube
#    namespace: lab-mafe-ci-cd
#    user: ngrok-sa
#  name: minikube
#current-context: minikube
#kind: Config
#preferences: {}
#users:
#- name: ngrok-sa
#  user: {}
