apiVersion: v1
kind: Service
metadata:
  name: laboratorio-mafe-service
  namespace: lab-mafe-ci-cd
spec:
  type: NodePort
  ports:
    - port: 8080   # Puerto expuesto por tu aplicación
      targetPort: 8080   # Puerto en el contenedor
      nodePort: 30001    # Puerto accesible desde fuera del clúster
  selector:
    app: laboratorio-mafe  # Selector que coincide con las etiquetas de tu despliegue
