name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-west-2"
      AWS_ACCOUNT_ID: "338287058401"
      ECR_REPOSITORY: "laboratorio_mafe"
      IMAGE_TAG: "latest"
      NAMESPACE: "lab-mafe-ci-cd"
      NGROK_URL: "https://10ba-186-144-144-107.ngrok-free.app"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Set execute permissions for deployment script
        run: chmod +x scripts/deploy_to_minikube.sh

      - name: Fetch latest Docker image from ECR
        run: |
          docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Minikube via Ngrok
        run: |
          export KUBECONFIG=kubeconfig
          kubectl apply -f deployment.yaml -n lab-mafe-ci-cd
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml
          ngrok start --all --config=kubernetes/ngrok.yml --region=us --authtoken=${{ secrets.NGROK_AUTH_TOKEN }} --log=stdout > ngrok.log &
          sleep 10
          echo "Ngrok tunnel URL:"
          cat ngrok.log | grep "Forwarding"
          echo "::set-output name=ngrok-url::$(cat ngrok.log | grep "Forwarding" | awk '{ print $NF }')"

      - name: Save Ngrok URL as environment variable
        id: ngrok
        run: echo "::set-env name=NGROK_URL::$(cat ngrok.log | grep 'Forwarding' | awk '{ print $NF }')"
      
      - name: Deploy to Minikube with Ngrok URL
        run: |
          sed -i "s|NGROK_URL|${{ env.NGROK_URL }}|g" kubernetes/ingress.yaml
          kubectl apply -f kubernetes/ingress.yaml

